# fly.toml app configuration file generated for late-star-337 on 2023-04-19T08:15:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "late-star-337"
primary_region = "atl"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
